# Generated by Django 5.2 on 2025-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_phone_number_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='otp',
            field=models.CharField(default='041282', max_length=6),
        ),
    ]
