# Generated by Django 5.2 on 2025-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='.', max_length=128),
        ),
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.CharField(default='.', max_length=24),
        ),
    ]
