# Generated by Django 5.2 on 2025-04-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_user_booking_name_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.CharField(default='.', max_length=256),
            preserve_default=False,
        ),
    ]
