# Generated by Django 5.2 on 2025-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
