# Generated by Django 5.2 on 2025-04-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_time_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='job_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
