# Generated by Django 5.2 on 2025-04-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bay_job_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bay',
            name='in_use_until',
        ),
        migrations.RemoveField(
            model_name='bay',
            name='job_start',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='bookings.bay')),
            ],
        ),
    ]
