# Generated by Django 5.2 on 2025-04-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_bay_in_use_until_remove_bay_job_start_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bookings.booking'),
        ),
    ]
