# Generated by Django 5.2 on 2025-04-23 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_job_booking'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
